name: ANewAgeUtilities
version: 2.0
author: stampler
main: me.stampler.core.Core
description: >
  Utility Plugin for A New Age.
commands:
  discord:
    description: Showcases Discord Link
  online:
    description: Shows Online Players
  info:
    description: Gives info about commands
  dwarvesafter:
    description: After Dwarves GUI
  orcsafter:
    description: After Orcs GUI
  menafter:
    description: After Men GUI
  elvesafter:
    description: After Men GUI
  evilmenafter:
    description: After Evil-Men GUI
  creaturesafter:
    description: After Creatures GUI
  factions:
    description: Opens Faction GUI