name: FactionPlugin
version: 2.0
author: stampler
main: me.stampler.core.Core
permissions:
description: >
  Core Plugin for LOTR 1.16.5
commands:
  discord:
    description: Showcases Discord Link
  online:
    description: Shows Online Players
  info:
    description: Gives info about commands
  dwarvesafter:
    description: After Dwarves GUI
  factions:
    description: Opens Faction GUI